export const servicesNames = [
	'Carpinteros',
	'Oftamologo',
	'Artesanos',
	'Diseñador gráfico',
	'Masajistas',
	'Alergólogo',
	'Banquetes para fiestas',
	'Quiropráctico',
	'Enfermero',
	'Notario',
	'Servicio de agua purificada',
	'Locutor',
	'Mariachi',
	'Veterinario',
	'Agente de viajes',
	'Zapatero',
	'Personal de limpieza del hogar',
	'Electricista',
	'Taxista',
	'Reparación de electrodomesticos',
	'Repartidores',
	'Pintor',
	'Manicurista',
	'Proctólogo',
	'Logistica de fiestas',
	'Renta mesas y sillas para eventos',
	'Exterminador de plagas',
];
